# Generated by Django 6.0.4 on 2026-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
