# Generated by Django 6.0.4 on 2026-06-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expo_push_token',
        ),
    ]
