# Generated by Django 6.0.4 on 2026-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='wants_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wants_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wants_sms',
            field=models.BooleanField(default=True),
        ),
    ]
