# Generated by Django 6.0.4 on 2026-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_patientprofile_wants_email_patientprofile_wants_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
