# Generated by Django 6.0.4 on 2026-06-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_medicalrecord_heart_rate_medicalrecord_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
