# Generated by Django 6.0.4 on 2026-06-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0004_patientprofile_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='wants_sms',
        ),
    ]
