# Generated by Django 6.0.4 on 2026-06-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0005_remove_patientprofile_wants_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='wants_email',
        ),
    ]
