# Generated by Django 6.0.4 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('Health & Wellness', 'Health & Wellness'), ('Pension Update', 'Pension Update'), ('Events', 'Events'), ('Emergency', 'Emergency'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('Standard Information', 'Standard Information'), ('Urgent', 'Urgent'), ('High Priority', 'High Priority')], default='Standard Information', max_length=100),
        ),
    ]
